### ISSUE TITLE
git-phlow workon fails to fetch when ssh-key is protected with a password

### ISSUE THREAD

**Issue by dangrondahl** [Praqma/git-phlow#265] opened 2017-10-18 19:56 UTC
It seems that when I have a password protected ssh-key, `workon` process does not prompt for this, but fails as shown in the example below. 
OS: Windows 10

```
git-phlow -v workon CODE-123
Exec: git status
Exec: git config --get phlow.service
Exec: git config --get phlow.issue-api
Exec: git config --get phlow.issue-web
Exec: git config --get phlow.remote
Exec: git config --get phlow.delivery-branch-prefix
Exec: git config --get phlow.integration-branch
Preparing workspace...
Exec: git fetch --all
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
error: Could not fetch origin
```

**Comment by buep** [comment] 2017-10-19 10:55
I can't reproduce this, but I also tried on Linux only with a password protected ssh-key attached to Github.

We will need more information...

What terminal are you using on Windows? 
Are you able to go into the repository and run the same command in the kind of terminal (e.g. powershell, git bash or command prompt) and get another result?

Can you share your git config file with us, or an anonymous version of it?

In our code we do not suppress anything and just call command line.

**Comment by dangrondahl** [comment] 2017-10-26 12:04
I think it is my terminals problem. I am using [cmder](cmder.net). 
When using git-bash it prompted me for my password through a dialog box.

The, somewhat temporary, solution in cmder is to run the command `start-ssh-agent.cmd` which solved this issue. However it could be nice that this worked _out-of-the-box_.

**Comment by buep** [comment] 2017-10-27 09:21
We will keep the issues for maybe later supporting more terminals and user-scenarios.

Adding it to backlog.

**Comment by groenborg** [comment] 2018-01-05 14:51
We have added a matrix for supported terminals, so we know which ones work and which does not. The problem comes with the emulated terminals on windows like Cmder and such. We do not have a fix right now for those but we will check back in the future. I will close this issue, and create a new one when it is time to check support for others

**Closed by groenborg** 2018-01-05 14:51 UTC

**Comment by buep** [comment] 2018-01-08 09:39
All right, I wrote #302 so we remember it.
